import bcrypt from 'bcryptjs';
import { pool, withTransaction } from './pool.js';

const users=[['Aravind Kumar','admin@orbit.local','Admin'],['Priya Sharma','sales@orbit.local','Sales'],['Rahul Varma','warehouse@orbit.local','Warehouse'],['Meera Iyer','accounts@orbit.local','Accounts']] as const;
const customers=[
['Lakshmi Reddy','9876543210','purchases@srilakshmitraders.in','Sri Lakshmi Traders','36ABCDE1234F1Z5','Wholesale','Begum Bazaar, Hyderabad, Telangana','Active','Requested the updated institutional price list.'],
['Vijay Kumar','9820012456','vijay@vijayawholesale.in','Vijaya Wholesale Mart','29AAACN2345Q1ZK','Wholesale','Chickpet, Bengaluru, Karnataka','Active','High-volume monthly account.'],
['Krishna Rao','9988776655','orders@saikrishna.in','Sai Krishna Distributors','37AACFW7821L1Z9','Distributor','Auto Nagar, Vijayawada, Andhra Pradesh','Lead','Catalogue shared; awaiting first order.'],
['Ananya Mehta','9000011112','ananya@metroretail.in','Metro Retail Supplies','27ABCPM5541R1ZP','Retail','Andheri East, Mumbai, Maharashtra','Active','Prefers consolidated weekly dispatches.'],
['Suresh Gupta','9848012345','buying@annapurnafoods.in','Annapurna Foods','36AAGFA8890B1Z8','Wholesale','Kukatpally, Hyderabad, Telangana','Active','Food products buyer.'],
['Kavya Nair','9949011122','kavya@kaverienterprises.in','Kaveri Enterprises','32AABCK7712L1Z6','Distributor','Ernakulam, Kochi, Kerala','Lead','Needs distribution territory proposal.'],
['Venkat Rao','9700011122','venkat@vagencies.in','Venkateswara Agencies','37AAEFV4421C1Z2','Distributor','Guntur, Andhra Pradesh','Active','Quarterly rate agreement.'],
['Farhan Ali','9885012211','farhan@deccanmart.in','Deccan Business Mart','36AADFD6608M1Z1','Retail','Banjara Hills, Hyderabad, Telangana','Active','Office consumables account.'],
['Neha Joshi','9819011100','neha@westerntrade.in','Western Trade Links','27AAAFW3012K1ZX','Wholesale','Bhiwandi, Maharashtra','Inactive','Paused procurement until next quarter.'],
['Arjun Singh','9893011122','arjun@centraldistributors.in','Central Distributors','23AAGFC7718H1Z4','Distributor','Indore, Madhya Pradesh','Active','Requires batch-wise delivery notes.'],
['Divya Menon','9447011223','divya@malabarsupplies.in','Malabar Supplies','32AALFM9982P1Z3','Wholesale','Kozhikode, Kerala','Lead','Follow up after sampling.'],
['Rakesh Patel','9974011223','rakesh@sabarmati.in','Sabarmati Trading Co.','24AAHFS5539A1Z7','Wholesale','Ahmedabad, Gujarat','Active','Packaging supplies buyer.'],
['Pooja Das','9830012277','pooja@easternretail.in','Eastern Retail Network','19AAGFE1187R1Z9','Retail','Salt Lake, Kolkata, West Bengal','Active','Eight retail outlets.'],
['Manoj Kulkarni','9766011299','manoj@puneoffice.in','Pune Office Needs','27AAMFP8814D1ZQ','Retail','Shivajinagar, Pune, Maharashtra','Lead','Requested credit terms.'],
['Sneha Bhat','9900012299','sneha@coastalagencies.in','Coastal Agencies','29AAJFC4491Q1Z5','Distributor','Mangaluru, Karnataka','Active','Coastal Karnataka distributor.'],
] as const;
const products=[
['Premium Basmati Rice 25kg','RICE-BAS-25','Food Staples',2850,48,15,'Hyderabad Central Warehouse'],['Refined Sunflower Oil 15L','OIL-SUN-15','Cooking Essentials',2190,9,12,'Hyderabad Central Warehouse'],['Whole Wheat Flour 10kg','FLOUR-WW-10','Food Staples',620,72,20,'Bengaluru Distribution Hub'],['Instant Coffee 500g','COFFEE-IN-500','Beverages',780,0,10,'Bengaluru Distribution Hub'],['Disposable Cups 500pc','CUPS-DSP-500','Food Service',410,34,12,'Vijayawada Storage Facility'],['Packaging Tape 48mm','TAPE-PKG-48','Packaging',95,120,30,'Hyderabad Central Warehouse'],['Office Paper A4 75gsm','PAPER-A4-75','Office Supplies',325,64,20,'Bengaluru Distribution Hub'],['Cleaning Liquid 5L','CLEAN-LIQ-5','Cleaning',540,11,15,'Hyderabad Central Warehouse'],['Packaged Snacks Assortment','SNACK-MIX-24','Food & Beverage',960,38,12,'Vijayawada Storage Facility'],['Beverage Cases 24x300ml','BEV-CASE-24','Beverages',1140,26,10,'Vijayawada Storage Facility'],['Paper Towels 12 Roll','TOWEL-12R','Paper Products',460,55,18,'Bengaluru Distribution Hub'],['Heavy Duty Garbage Bags','BAG-GRB-HD','Cleaning',290,19,10,'Hyderabad Central Warehouse'],['Corrugated Box Medium','BOX-COR-M','Packaging',68,210,50,'Vijayawada Storage Facility'],['Thermal Billing Rolls 50pc','ROLL-THM-50','Office Supplies',850,29,10,'Bengaluru Distribution Hub'],['Hand Wash 5L','WASH-HND-5','Cleaning',610,16,12,'Hyderabad Central Warehouse'],['Green Tea 100 Bags','TEA-GRN-100','Beverages',490,42,15,'Bengaluru Distribution Hub'],['Brown Sugar 5kg','SUGAR-BRN-5','Food Staples',390,25,10,'Vijayawada Storage Facility'],['Aluminium Foil 72m','FOIL-AL-72','Food Service',375,7,10,'Hyderabad Central Warehouse'],['Permanent Markers 10pc','MARK-PM-10','Office Supplies',220,44,15,'Bengaluru Distribution Hub'],['Stretch Film 500mm','FILM-STR-500','Packaging',690,13,15,'Vijayawada Storage Facility'],
] as const;

try{
 await withTransaction(async(db)=>{
  const passwordHash=await bcrypt.hash('Orbit@123',12);
  for(const [name,email,role] of users)await db.query(`INSERT INTO users(name,email,password_hash,role) VALUES($1,$2,$3,$4) ON CONFLICT(email) DO UPDATE SET name=EXCLUDED.name,role=EXCLUDED.role,password_hash=EXCLUDED.password_hash`,[name,email,passwordHash,role]);
  const adminId=(await db.query("SELECT id FROM users WHERE email='admin@orbit.local'")).rows[0].id;
  const salesId=(await db.query("SELECT id FROM users WHERE email='sales@orbit.local'")).rows[0].id;
  for(let index=0;index<customers.length;index++){const [name,mobile,email,business,gst,type,address,status,notes]=customers[index]!;const due=index<4?new Date(Date.now()+(index-1)*86400000).toISOString().slice(0,10):null;await db.query(`INSERT INTO customers(customer_name,mobile,email,business_name,gst_number,customer_type,address,status,follow_up_date,notes,created_by) SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11 WHERE NOT EXISTS(SELECT 1 FROM customers WHERE mobile=$2::varchar)`,[name,mobile,email,business,gst,type,address,status,due,notes,salesId]);}
  for(const row of products){const inserted=await db.query(`INSERT INTO products(product_name,sku,category,unit_price,current_stock,minimum_stock,warehouse_location,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(sku) DO NOTHING RETURNING id,current_stock`,[...row,adminId]);if(inserted.rows[0]&&inserted.rows[0].current_stock>0)await db.query(`INSERT INTO stock_movements(product_id,quantity_changed,movement_type,reason,created_by) VALUES($1,$2,'IN','Opening stock',$3)`,[inserted.rows[0].id,inserted.rows[0].current_stock,adminId]);}
  const customerRows=await db.query(`SELECT id,business_name,follow_up_date FROM customers ORDER BY created_at LIMIT 4`);for(const customer of customerRows.rows)await db.query(`INSERT INTO customer_followups(customer_id,note,next_follow_up_date,scheduled_at,created_by) SELECT $1,$2,$3,$3::date + TIME '10:00',$4 WHERE NOT EXISTS(SELECT 1 FROM customer_followups WHERE customer_id=$1)`,[customer.id,'Discussed current requirements and shared updated pricing.',customer.follow_up_date,salesId]);
  const demoCount=(await db.query(`SELECT COUNT(*)::int count FROM challans WHERE notes LIKE 'Seed demo%'`)).rows[0].count;
  if(demoCount===0){const demoCustomers=(await db.query(`SELECT * FROM customers WHERE status='Active' ORDER BY created_at LIMIT 4`)).rows;const demoProducts=(await db.query(`SELECT * FROM products WHERE current_stock>10 ORDER BY created_at LIMIT 6`)).rows;for(let index=0;index<4;index++){const customer=demoCustomers[index],first=demoProducts[index],second=demoProducts[index+1];if(!customer||!first||!second)continue;const confirmed=index<3,lines=[{product:first,quantity:index+2},{product:second,quantity:2}],totalQuantity=lines.reduce((sum,line)=>sum+line.quantity,0),totalAmount=lines.reduce((sum,line)=>sum+Number(line.product.unit_price)*line.quantity,0),sequence=(await db.query(`SELECT nextval('challan_number_seq') value`)).rows[0].value,number=`CH-${new Date().getFullYear()}-${String(sequence).padStart(6,'0')}`,snapshot={customer_name:customer.customer_name,business_name:customer.business_name,mobile:customer.mobile,email:customer.email,address:customer.address,gst_number:customer.gst_number},challan=(await db.query(`INSERT INTO challans(challan_number,customer_id,customer_snapshot,total_quantity,total_amount,status,notes,created_by,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,NOW()-($9::int*INTERVAL '1 day')) RETURNING id`,[number,customer.id,snapshot,totalQuantity,totalAmount,confirmed?'Confirmed':'Draft',`Seed demo ${index+1}`,salesId,index])).rows[0];for(const line of lines){await db.query(`INSERT INTO challan_items(challan_id,product_id,product_name,sku,unit_price,quantity,line_total) VALUES($1,$2,$3,$4,$5,$6,$7)`,[challan.id,line.product.id,line.product.product_name,line.product.sku,line.product.unit_price,line.quantity,Number(line.product.unit_price)*line.quantity]);if(confirmed){await db.query(`UPDATE products SET current_stock=current_stock-$1 WHERE id=$2`,[line.quantity,line.product.id]);await db.query(`INSERT INTO stock_movements(product_id,quantity_changed,movement_type,reason,challan_id,created_by) VALUES($1,$2,'OUT',$3,$4,$5)`,[line.product.id,line.quantity,`Issued through ${number}`,challan.id,salesId]);}}}}
  await db.query(`INSERT INTO audit_logs(actor_id,action,entity_type,description) SELECT $1,'workspace.seeded','system','Realistic Orbit demo workspace initialized.' WHERE NOT EXISTS(SELECT 1 FROM audit_logs WHERE action='workspace.seeded')`,[adminId]);
 });
 console.log('Seed complete. Demo password for all roles: Orbit@123');
}finally{await pool.end();}
