import{useEffect,useMemo,useRef,useState}from'react';import{useNavigate,useSearchParams}from'react-router-dom';import{ArrowLeft,CheckCircle2,ChevronRight,Minus,PackagePlus,Plus,ReceiptText,Search,Trash2}from'lucide-react';
import{api,queryString}from'../lib/api.js';import{currency}from'../lib/format.js';import{ConfirmDialog,EmptyState,Field}from'../components/UI.jsx';import{useToast}from'../context/ToastContext.jsx';
export default function ChallanBuilder(){
 const[params]=useSearchParams(),navigate=useNavigate(),toast=useToast();const[customer,setCustomer]=useState(null),[items,setItems]=useState([]),[notes,setNotes]=useState(''),[busy,setBusy]=useState(false),[confirming,setConfirming]=useState(false);
 useEffect(()=>{const id=params.get('customer');if(id)api(`/customers/${id}`).then(setCustomer).catch(()=>{})},[params]);
 const total=useMemo(()=>items.reduce((sum,item)=>sum+Number(item.unit_price)*item.quantity,0),[items]),qty=items.reduce((sum,item)=>sum+item.quantity,0),invalid=items.some(item=>item.quantity>item.current_stock);
 const add=product=>{if(!items.some(item=>item.id===product.id))setItems(current=>[...current,{...product,quantity:1}])};const setQty=(id,value)=>setItems(current=>current.map(item=>item.id===id?{...item,quantity:Math.max(1,Number(value)||1)}:item));
 const submit=async status=>{if(!customer)return toast.error('Choose a customer first.');if(!items.length)return toast.error('Add at least one product.');if(status==='Confirmed'&&!confirming){setConfirming(true);return}setBusy(true);try{const result=await api('/challans',{method:'POST',body:{customer_id:customer.id,items:items.map(item=>({product_id:item.id,quantity:item.quantity})),notes,status}});toast.success(status==='Confirmed'?'Challan confirmed and stock updated.':'Draft challan saved.');navigate(`/challans/${result.id}`)}catch(error){toast.error(error.message)}finally{setBusy(false);setConfirming(false)}};
 return <><button className="back" onClick={()=>navigate('/challans')}><ArrowLeft/>Back to challans</button><div className="builder-heading"><div><div className="eyebrow neutral"><ReceiptText/> NEW SALES CHALLAN</div><h1>New Sales Challan</h1><p>Select a customer, add products, and review before confirming.</p></div><div className="steps"><span className={customer?'done':'active'}>{customer?<CheckCircle2/>:'1'}<b>Customer</b></span><i/><span className={items.length?'done':customer?'active':''}>{items.length?<CheckCircle2/>:'2'}<b>Products</b></span><i/><span className={items.length?'active':''}>3<b>Review</b></span></div></div><div className="builder-grid"><div className="builder-main">
 <section className="panel builder-section"><header><div><span>01</span><div><h2>Customer</h2><p>Search active customers from the server</p></div></div>{customer&&<button onClick={()=>setCustomer(null)}>Change</button>}</header>{customer?<div className="selected-customer"><span>{customer.customer_name[0]}</span><div><b>{customer.business_name}</b><small>{customer.customer_name} · {customer.mobile} · {customer.gst_number||'No GSTIN'} · {customer.status}</small></div><CheckCircle2/></div>:<ServerPicker type="customers" placeholder="Search active customers…" onChoose={setCustomer}/>}</section>
 <section className="panel builder-section"><header><div><span>02</span><div><h2>Products</h2><p>Stock is revalidated atomically on confirmation</p></div></div></header><ServerPicker type="products" placeholder="Search product, SKU, or category…" excluded={items.map(item=>item.id)} onChoose={add}/>{items.length?<div className="line-items"><div className="line-head"><span>Product</span><span>Price</span><span>Quantity</span><span>Amount</span><span/></div>{items.map(item=><div className="line-row" key={item.id}><div><span className="product-icon"><PackagePlus/></span><b>{item.product_name}</b><small>{item.sku} · {item.current_stock} available</small></div><span>{currency(item.unit_price)}</span><div className="qty"><button type="button" aria-label="Decrease quantity" onClick={()=>setQty(item.id,item.quantity-1)}><Minus/></button><input aria-label={`Quantity for ${item.product_name}`} type="number" min="1" value={item.quantity} onChange={e=>setQty(item.id,e.target.value)}/><button type="button" aria-label="Increase quantity" onClick={()=>setQty(item.id,item.quantity+1)}><Plus/></button></div><strong>{currency(item.unit_price*item.quantity)}</strong><button type="button" className="delete" aria-label={`Remove ${item.product_name}`} onClick={()=>setItems(current=>current.filter(value=>value.id!==item.id))}><Trash2/></button>{item.quantity>item.current_stock&&<small className="stock-error">Only {item.current_stock} units available.</small>}</div>)}</div>:<EmptyState title="No products added" message="Search inventory above and add products to this challan."/>}</section>
 <section className="panel builder-section"><header><div><span>03</span><div><h2>Review note</h2><p>Optional delivery or handling instructions</p></div></div></header><Field label="Internal / delivery note"><textarea rows="4" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Add instructions or reference numbers…"/></Field></section></div>
 <aside className="order-summary"><div className="panel"><span className="summary-label">CHALLAN SUMMARY</span><h2>{customer?.business_name||'No customer selected'}</h2><div className="summary-lines"><span>Products <b>{items.length}</b></span><span>Total quantity <b>{qty}</b></span><span>Total value <b>{currency(total)}</b></span></div><div className="grand-total"><span>Total value</span><strong>{currency(total)}</strong><small>Taxes handled at invoicing</small></div><button className="secondary wide" disabled={busy} onClick={()=>submit('Draft')}>Save Draft</button><button className="primary wide" disabled={busy||invalid} onClick={()=>submit('Confirmed')}>{busy?'Processing…':'Confirm Challan'}<ChevronRight/></button><p className="safe-note"><CheckCircle2/>Transactional stock validation enabled</p></div></aside></div>
 <ConfirmDialog open={confirming} onClose={()=>setConfirming(false)} onConfirm={()=>submit('Confirmed')} title="Confirm this sales challan?" message={`${qty} units will be removed from inventory immediately. This operation is atomic.`} confirmLabel="Confirm Challan" tone="primary" loading={busy}/></>;
}
function ServerPicker({type,placeholder,onChoose,excluded=[]}){const[query,setQuery]=useState(''),[items,setItems]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),timer=useRef();useEffect(()=>{clearTimeout(timer.current);setError('');if(query.trim().length<2){setItems([]);return}timer.current=setTimeout(async()=>{setLoading(true);try{const result=await api(`/${type}${queryString({search:query.trim(),status:type==='customers'?'Active':undefined,limit:8})}`);setItems(result.data.filter(item=>!excluded.includes(item.id)))}catch(err){setError(err.message)}finally{setLoading(false)}},220);return()=>clearTimeout(timer.current)},[query,type,excluded.join('|')]);return <div className="picker"><div className="search-input"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={placeholder}/></div>{query.length>=2&&<div className="picker-results">{loading?<p>Searching…</p>:error?<p>{error}</p>:items.length?items.map(item=><button type="button" key={item.id} onClick={()=>{onChoose(item);setQuery('');setItems([])}} disabled={type==='products'&&!item.current_stock}><span className={type==='customers'?'avatar':'product-icon'}>{type==='customers'?item.customer_name[0]:<PackagePlus/>}</span><div><b>{type==='customers'?item.business_name:item.product_name}</b><small>{type==='customers'?`${item.customer_name} · ${item.mobile}`:`${item.sku} · ${item.current_stock} available`}</small></div>{type==='products'&&<strong>{currency(item.unit_price)}</strong>}<ChevronRight/></button>):<p>No matching records</p>}</div>}</div>}
