import{useCallback,useEffect,useState}from'react';import{useNavigate,useParams}from'react-router-dom';import{ArrowLeft,Building2,CalendarDays,FileText,Mail,MapPin,MessageSquarePlus,Pencil,Phone,Plus,ReceiptText,UserRound}from'lucide-react';
import{api}from'../lib/api.js';import{currency,date}from'../lib/format.js';import{Avatar,Badge,DetailSkeleton,EmptyState,ErrorState,Field,MetricCard,Modal,Tabs}from'../components/UI.jsx';import{useAuth}from'../context/AuthContext.jsx';import{useToast}from'../context/ToastContext.jsx';
export default function CustomerDetail(){
 const{id}=useParams(),navigate=useNavigate(),{can}=useAuth(),toast=useToast();const[data,setData]=useState(null),[error,setError]=useState(''),[follow,setFollow]=useState(false),[editing,setEditing]=useState(null),[tab,setTab]=useState('overview');
 const load=useCallback(async()=>{setError('');try{setData(await api(`/customers/${id}`))}catch(err){setData(null);setError(err.message)}},[id]);useEffect(()=>{load()},[load]);
 if(error)return <ErrorState title="Unable to load customer" message={error} retry={load}/>;if(!data)return <DetailSkeleton/>;const metrics=data.metrics||{};
 return <><button className="back" onClick={()=>navigate('/customers')}><ArrowLeft/>Back to Customers</button><div className="detail-hero"><Avatar name={data.customer_name} size="xl"/><div><div><Badge>{data.status}</Badge><span className="soft-tag">{data.customer_type}</span></div><h1>{data.business_name}</h1><p><UserRound/>{data.customer_name} · Owner {data.owner_name||'Unassigned'}</p></div><div className="detail-actions"><button className="secondary" onClick={()=>setEditing({...data})}><Pencil/>Edit</button><button className="secondary" onClick={()=>setFollow(true)}><MessageSquarePlus/>Add follow-up</button><button className="primary" onClick={()=>navigate(`/challans/new?customer=${id}`)}><Plus/>Create challan</button></div></div>
 <section className="stat-grid customer-metrics"><MetricCard label="Total challans" value={metrics.total_challans||0} icon={ReceiptText}/><MetricCard label="Sales value" value={currency(metrics.sales_value||0)}/><MetricCard label="Last purchase" value={date(metrics.last_purchase)}/><MetricCard label="Next follow-up" value={date(data.follow_up_date)} icon={CalendarDays} tone={data.follow_up_date&&new Date(data.follow_up_date)<new Date()?'danger':'brand'}/></section>
 <Tabs items={[{value:'overview',label:'Overview'},{value:'followups',label:`Follow-ups (${data.followups.length})`},{value:'challans',label:`Challans (${data.challans.length})`},{value:'activity',label:'Activity'}]} value={tab} onChange={setTab}/>
 {tab==='overview'&&<section className="panel info-card customer-overview"><header><h2>Contact & business</h2></header><dl><div><dt><UserRound/>Contact person</dt><dd>{data.customer_name}</dd></div><div><dt><Phone/>Phone</dt><dd><a href={`tel:${data.mobile}`}>{data.mobile}</a></dd></div><div><dt><Mail/>Email</dt><dd>{data.email?<a href={`mailto:${data.email}`}>{data.email}</a>:'Not provided'}</dd></div><div><dt><FileText/>GSTIN</dt><dd>{data.gst_number||'Not provided'}</dd></div><div><dt><MapPin/>Address</dt><dd>{data.address}</dd></div><div><dt><UserRound/>Owner</dt><dd>{data.owner_name||'Unassigned'}</dd></div><div><dt><CalendarDays/>Customer since</dt><dd>{date(data.created_at)}</dd></div></dl>{data.notes&&<div className="note-box"><b>Account note</b><p>{data.notes}</p></div>}</section>}
 {tab==='followups'&&<section className="panel timeline-card"><header><div><h2>Follow-up history</h2><p>Conversations and next steps</p></div></header>{data.followups.length?data.followups.map(item=><Timeline key={item.id} hot={item.display_status==='Overdue'} title={item.note} detail={`${item.display_status} · ${item.scheduled_at?date(item.scheduled_at,{dateStyle:'medium',timeStyle:'short'}):'No schedule'}`} meta={`${item.created_by_name||'System'} · ${date(item.created_at,{dateStyle:'medium',timeStyle:'short'})}`}/>):<EmptyState title="No follow-ups logged" message="Add the next customer touchpoint to start the relationship timeline."/>}</section>}
 {tab==='challans'&&<section className="panel orders-card"><header><div><h2>Sales history</h2><p>Documents for this customer</p></div><ReceiptText/></header>{data.challans.length?data.challans.map(item=><button key={item.id} onClick={()=>navigate(`/challans/${item.id}`)}><div><b>{item.challan_number}</b><small>{date(item.created_at)} · {item.total_quantity} units</small></div><Badge>{item.status}</Badge><strong>{currency(item.total_amount)}</strong></button>):<EmptyState title="No sales challans yet" message="Create a draft or confirmed challan from the action above."/>}</section>}
 {tab==='activity'&&<section className="panel timeline-card"><header><div><h2>Account activity</h2><p>Audited customer changes and workflow events</p></div></header>{data.activity.length?data.activity.map(item=><Timeline key={item.id} title={item.description} detail={item.action.replaceAll('.',' · ')} meta={`${item.actor_name||'System'} · ${date(item.created_at,{dateStyle:'medium',timeStyle:'short'})}`}/>):<EmptyState title="No audited activity yet"/>}</section>}
 <FollowupModal open={follow} close={()=>setFollow(false)} id={id} done={()=>{setFollow(false);toast.success('Follow-up added');load()}}/><CustomerEdit value={editing} setValue={setEditing} close={()=>setEditing(null)} done={()=>{setEditing(null);toast.success('Customer updated');load()}}/></>;
}
function Timeline({title,detail,meta,hot=false}){return <div className={`timeline-row ${hot?'overdue-event':''}`}><i/><div><b>{title}</b><p>{detail}</p><small>{meta}</small></div></div>}
function FollowupModal({open,close,id,done}){
 const[form,setForm]=useState({note:'',next_follow_up_date:''}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const submit=async event=>{event.preventDefault();setBusy(true);setError('');try{await api(`/customers/${id}/followups`,{method:'POST',body:form});setForm({note:'',next_follow_up_date:''});done()}catch(err){setError(err.message)}finally{setBusy(false)}};
 return <Modal open={open} onClose={close} title="Add follow-up" subtitle="Capture the conversation and plan the next touchpoint.">{open&&<form onSubmit={submit}>{error&&<div className="form-error" role="alert">{error}</div>}<Field label="Follow-up note" required><textarea rows="5" value={form.note} onChange={e=>setForm({...form,note:e.target.value})} required/></Field><Field label="Next follow-up date"><input type="date" value={form.next_follow_up_date} onChange={e=>setForm({...form,next_follow_up_date:e.target.value})}/></Field><div className="form-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={busy}>{busy?'Adding…':'Add follow-up'}</button></div></form>}</Modal>;
}
function CustomerEdit({value,setValue,close,done}){const[busy,setBusy]=useState(false),[errors,setErrors]=useState({});if(!value)return null;const set=(key,next)=>setValue({...value,[key]:next});const submit=async event=>{event.preventDefault();setBusy(true);setErrors({});try{await api(`/customers/${value.id}`,{method:'PUT',body:value});done()}catch(error){setErrors(error.errors||{form:[error.message]})}finally{setBusy(false)}};return <Modal open title="Edit customer" subtitle="Changes are recorded in the activity timeline." onClose={close} size="large"><form onSubmit={submit} className="form-grid">{errors.form&&<div className="form-error full">{errors.form[0]}</div>}<Field label="Contact name" error={errors.customer_name?.[0]}><input value={value.customer_name} onChange={e=>set('customer_name',e.target.value)} required/></Field><Field label="Business name" error={errors.business_name?.[0]}><input value={value.business_name} onChange={e=>set('business_name',e.target.value)} required/></Field><Field label="Mobile" error={errors.mobile?.[0]}><input value={value.mobile} onChange={e=>set('mobile',e.target.value)} required/></Field><Field label="Email" error={errors.email?.[0]}><input type="email" value={value.email||''} onChange={e=>set('email',e.target.value)}/></Field><Field label="GSTIN" error={errors.gst_number?.[0]}><input value={value.gst_number||''} onChange={e=>set('gst_number',e.target.value.toUpperCase())}/></Field><Field label="Type"><select value={value.customer_type} onChange={e=>set('customer_type',e.target.value)}><option>Retail</option><option>Wholesale</option><option>Distributor</option></select></Field><Field label="Status"><select value={value.status} onChange={e=>set('status',e.target.value)}><option>Lead</option><option>Active</option><option>Inactive</option></select></Field><Field label="Next follow-up"><input type="date" value={value.follow_up_date?.slice(0,10)||''} onChange={e=>set('follow_up_date',e.target.value)}/></Field><Field label="Address" error={errors.address?.[0]}><textarea value={value.address} onChange={e=>set('address',e.target.value)} required/></Field><Field label="Notes"><textarea value={value.notes||''} onChange={e=>set('notes',e.target.value)}/></Field><div className="form-actions full"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':'Save changes'}</button></div></form></Modal>}
