import{useCallback,useEffect,useMemo,useState}from'react';
import{useNavigate}from'react-router-dom';
import{Area,AreaChart,Cell,Pie,PieChart,ResponsiveContainer,Tooltip as ChartTooltip,XAxis}from'recharts';
import{ArrowDownLeft,ArrowUpRight,Boxes,CalendarClock,ChevronRight,CircleDollarSign,PackageCheck,Plus,TriangleAlert,UsersRound,WandSparkles}from'lucide-react';
import{api}from'../lib/api.js';import{currency,date}from'../lib/format.js';
import{Badge,DashboardSkeleton,EmptyState,ErrorState,MetricCard}from'../components/UI.jsx';import{useAuth}from'../context/AuthContext.jsx';

const greetings={Admin:'across your operations',Sales:'across your customer pipeline',Warehouse:'across inventory and fulfilment',Accounts:'across confirmed sales'};
export default function Dashboard(){
 const[data,setData]=useState(null),[error,setError]=useState(''),[range,setRange]=useState('30D'),navigate=useNavigate(),{user}=useAuth();
 const load=useCallback(async()=>{setError('');try{setData(await api(`/dashboard?range=${range}`))}catch(err){setData(null);setError(err.message)}},[range]);useEffect(()=>{load()},[load]);
 const now=useMemo(()=>new Intl.DateTimeFormat('en-IN',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date()),[]);const hour=new Date().getHours(),greeting=hour<12?'Good morning':hour<17?'Good afternoon':'Good evening';
 if(error)return <ErrorState title="Unable to load your dashboard" message={error} retry={load}/>;if(!data)return <DashboardSkeleton/>;
 const s=data.summary,showInventory=user.role!=='Accounts',showSales=user.role!=='Warehouse',showCrm=['Admin','Sales'].includes(user.role);
 const roleStats=user.role==='Warehouse'?[['Inventory value',currency(s.inventory_value),'Live valuation',CircleDollarSign,'brand'],['Products tracked',s.products,'Across all warehouses',Boxes,'info'],['Low stock',s.low_stock,'At or below minimum',TriangleAlert,'warning'],['Out of stock',s.out_of_stock,'Immediate attention',PackageCheck,'danger']]:user.role==='Accounts'?[['Confirmed sales',currency(s.revenue),'Accounting-visible sales',CircleDollarSign,'brand'],['Confirmed challans',s.confirmed_challans,'Ready for review',PackageCheck,'info'],['Confirmed units',s.confirmed_units,'Dispatched units',Boxes,'success'],['Average challan',currency(s.average_challan_value),'Confirmed documents',CircleDollarSign,'warning']]:[['Total sales',currency(s.revenue),'Confirmed challans',CircleDollarSign,'brand'],['Active customers',s.active_customers,`${s.total_customers} total relationships`,UsersRound,'info'],['Products',s.products,'Tracked inventory SKUs',Boxes,'success'],['Today’s follow-ups',s.todays_followups,`${s.low_stock} low-stock alerts`,CalendarClock,'warning']];
 const cta=user.role==='Warehouse'?['Adjust stock','/products']:user.role==='Accounts'?['Review challans','/challans']:['Create challan','/challans/new'];
 return <><div className="page-heading"><div><div className="eyebrow neutral"><WandSparkles/> {now.toUpperCase()}</div><h1>{greeting}, {user.name.split(' ')[0]}.</h1><p>Here’s what’s happening {greetings[user.role]}.</p><span className="role-chip">{user.role} workspace</span></div><button className="primary" onClick={()=>navigate(cta[1])}>{cta[0]} <ArrowUpRight/></button></div>
 <section className="stat-grid">{roleStats.map(([label,value,detail,Icon,tone])=><MetricCard key={label} label={label} value={value} detail={detail} icon={Icon} tone={tone}/>)}</section>
 <section className="dashboard-grid">
 {showSales&&<article className="panel chart-panel"><header><div><h2>Sales overview</h2><p>Confirmed challan value</p></div><div className="range-tabs" aria-label="Sales range">{['7D','30D','90D','12M'].map(value=><button className={range===value?'active':''} key={value} onClick={()=>setRange(value)}>{value}</button>)}</div></header><div className="chart-total"><strong>{currency(s.revenue)}</strong><span>All-time confirmed</span></div><ResponsiveContainer width="100%" height={240}><AreaChart data={data.revenueTrend}><XAxis dataKey="label" axisLine={false} tickLine={false} minTickGap={28}/><ChartTooltip formatter={currency}/><Area type="monotone" dataKey="value" stroke="var(--brand)" strokeWidth={3} fill="var(--brand-subtle)"/></AreaChart></ResponsiveContainer></article>}
 {showInventory&&<DonutPanel title="Inventory health" subtitle="Current SKU availability" data={data.inventoryHealth}/>} {showCrm&&<DonutPanel title="Customer status" subtitle="Lead, active, and inactive" data={data.customerStatus}/>}
 {showInventory&&<article className="panel recent"><header><div><h2>Recent stock movements</h2><p>Latest inventory activity</p></div>{['Admin','Warehouse'].includes(user.role)&&<button onClick={()=>navigate('/stock-movements')}>View all</button>}</header>{data.recentMovements.length?<div className="operational-list">{data.recentMovements.map(m=><button key={m.id} onClick={()=>navigate(`/products?product=${m.product_id}`)}><span className={`movement-symbol ${m.movement_type}`}>{m.movement_type==='IN'?<ArrowDownLeft/>:<ArrowUpRight/>}</span><div><b>{m.product_name}</b><small>{m.sku} · {m.reason}</small></div><strong>{m.movement_type==='IN'?'+':'−'}{m.quantity_changed}</strong></button>)}</div>:<EmptyState title="No stock movements yet" message="Receipts and issued stock will appear here."/>}</article>}
 <article className="panel recent dashboard-wide"><header><div><h2>Recent challans</h2><p>{['Warehouse','Accounts'].includes(user.role)?'Confirmed documents only':'Latest sales activity'}</p></div><button onClick={()=>navigate('/challans')}>View all</button></header>{data.recentChallans.length?<div className="table-wrap"><table><thead><tr><th>Challan</th><th>Customer</th><th>Status</th><th>Value</th><th>Date</th></tr></thead><tbody>{data.recentChallans.map(c=><tr tabIndex="0" key={c.id} onClick={()=>navigate(`/challans/${c.id}`)} onKeyDown={e=>e.key==='Enter'&&navigate(`/challans/${c.id}`)}><td><b>{c.challan_number}</b></td><td>{c.business_name}</td><td><Badge>{c.status}</Badge></td><td><b>{currency(c.total_amount)}</b></td><td>{date(c.created_at)}</td></tr>)}</tbody></table></div>:<EmptyState title="No challans yet" message="Sales documents will appear here."/>}</article>
 {showCrm&&<article className="panel followup-card"><header><div><h2>Today’s follow-ups</h2><p>Prioritized CRM agenda</p></div><button onClick={()=>navigate('/follow-ups')}>Open agenda</button></header>{data.followups.length?data.followups.map(f=><button key={f.id} onClick={()=>navigate(`/customers/${f.id}`)}><span className={new Date(f.follow_up_date)<new Date()?'date-tile hot':'date-tile'}><b>{date(f.follow_up_date,{day:'2-digit'})}</b><small>{date(f.follow_up_date,{month:'short'}).toUpperCase()}</small></span><div><b>{f.business_name}</b><small>{f.customer_name} · {f.customer_type}</small></div><ChevronRight/></button>):<EmptyState title="No follow-ups today" message="Your schedule is clear. New customer follow-ups will appear here."/>}</article>}
 <QuickActions role={user.role} navigate={navigate}/>
 </section></>;
}
function DonutPanel({title,subtitle,data}){const colors=['var(--success)','var(--warning)','var(--danger)','var(--info)'];return <article className="panel health-panel"><header><div><h2>{title}</h2><p>{subtitle}</p></div></header><ResponsiveContainer width="100%" height={160}><PieChart><Pie data={data} dataKey="value" nameKey="status" innerRadius={48} outerRadius={70}>{data.map((item,index)=><Cell key={item.status} fill={colors[index%colors.length]}/>)}</Pie><ChartTooltip/></PieChart></ResponsiveContainer><div className="health-legend">{data.map((item,index)=><span key={item.status}><i style={{background:colors[index%colors.length]}}/>{item.status}<b>{item.value}</b></span>)}</div></article>}
function QuickActions({role,navigate}){const actions=role==='Admin'?[['New customer','/customers?create=1'],['New challan','/challans/new'],['Add product','/products?create=1']]:role==='Sales'?[['New customer','/customers?create=1'],['New challan','/challans/new'],['Follow-up agenda','/follow-ups']]:role==='Warehouse'?[['Add product','/products?create=1'],['Adjust stock','/products'],['Stock ledger','/stock-movements']]:[['Review challans','/challans'],['Open analytics','/analytics']];return <article className="panel quick-actions"><header><div><h2>Quick actions</h2><p>Role-aware shortcuts</p></div></header>{actions.map(([label,to])=><button key={label} onClick={()=>navigate(to)}><Plus/>{label}<ChevronRight/></button>)}</article>}
