import{useCallback,useEffect,useState}from'react';import{CalendarClock,Check,ChevronRight,Clock3,Search}from'lucide-react';import{useNavigate}from'react-router-dom';import{api,queryString}from'../lib/api.js';import{date}from'../lib/format.js';import{ConfirmDialog,EmptyState,ErrorState,Field,Modal,Pagination,TableSkeleton}from'../components/UI.jsx';import{useToast}from'../context/ToastContext.jsx';
const tabs=[['today','Today'],['overdue','Overdue'],['upcoming','Upcoming'],['completed','Completed']];
export default function Followups(){
 const[data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reschedule,setReschedule]=useState(null),[completing,setCompleting]=useState(null);const[query,setQuery]=useState({search:'',date:'today',status:'',customer_id:'',created_by:'',date_from:'',date_to:'',page:1,limit:10});const navigate=useNavigate(),toast=useToast();
 const load=useCallback(async()=>{setError('');try{setData(await api(`/followups${queryString(query)}`))}catch(err){setError(err.message);setData(null)}},[query]);useEffect(()=>{const timer=setTimeout(load,200);return()=>clearTimeout(timer)},[load]);const set=(key,value)=>setQuery(current=>({...current,[key]:value,page:1}));
 const complete=async()=>{const item=completing;setBusy(true);try{await api(`/followups/${item.id}/complete`,{method:'PATCH',body:{}});toast.success(`Follow-up completed for ${item.business_name}.`);setCompleting(null);setData(current=>({...current,data:current.data.filter(value=>value.id!==item.id),summary:{...current.summary,completed:Number(current.summary.completed)+1,overdue:Math.max(0,Number(current.summary.overdue)-(item.display_status==='Overdue'?1:0)),due_today:Math.max(0,Number(current.summary.due_today)-(new Date(item.scheduled_at).toDateString()===new Date().toDateString()?1:0))}}))}catch(err){toast.error(err.message)}finally{setBusy(false)}};
 const saveReschedule=async event=>{event.preventDefault();setBusy(true);try{await api(`/followups/${reschedule.id}/reschedule`,{method:'POST',body:{scheduled_at:new Date(reschedule.next_at).toISOString(),note:reschedule.new_note||undefined}});toast.success(`Follow-up rescheduled for ${reschedule.business_name}.`);setReschedule(null);await load()}catch(err){toast.error(err.message)}finally{setBusy(false)}};
 const active=query.status==='Completed'?'completed':query.date||'today',summary=data?.summary;
 return <><div className="page-heading"><div><div className="eyebrow neutral"><CalendarClock/> CRM AGENDA</div><h1>Follow-ups</h1><p>Complete, reschedule, and review every customer conversation.</p></div></div>{summary&&<section className="followup-summary"><button onClick={()=>setQuery({...query,date:'today',status:'',page:1})}><small>Due today</small><b>{summary.due_today}</b></button><button onClick={()=>setQuery({...query,date:'overdue',status:'',page:1})}><small>Overdue</small><b>{summary.overdue}</b></button><button onClick={()=>setQuery({...query,date:'upcoming',status:'',page:1})}><small>Upcoming</small><b>{summary.upcoming}</b></button><button onClick={()=>setQuery({...query,date:'',status:'Completed',page:1})}><small>Completed</small><b>{summary.completed}</b></button></section>}
 <section className="panel list-panel"><div className="followup-tabs">{tabs.map(([value,label])=><button key={value} className={active===value?'active':''} onClick={()=>setQuery(current=>({...current,date:value==='completed'?'':value,status:value==='completed'?'Completed':'',page:1}))}>{label}</button>)}</div><div className="list-toolbar"><div className="search-input"><Search/><input value={query.search} onChange={e=>set('search',e.target.value)} placeholder="Search customer, business, or note…"/></div><select value={query.customer_id} onChange={e=>set('customer_id',e.target.value)}><option value="">All customers</option>{data?.customers?.map(customer=><option key={customer.id} value={customer.id}>{customer.business_name}</option>)}</select><select value={query.created_by} onChange={e=>set('created_by',e.target.value)}><option value="">All owners</option>{data?.users?.map(user=><option key={user.id} value={user.id}>{user.name}</option>)}</select><input aria-label="From date" type="date" value={query.date_from} onChange={e=>set('date_from',e.target.value)}/><input aria-label="To date" type="date" value={query.date_to} onChange={e=>set('date_to',e.target.value)}/></div>
 {error?<ErrorState title="Unable to load follow-ups" message={error} retry={load}/>:!data?<TableSkeleton columns={6}/>:data.data.length?<><div className="operational-list">{data.data.map(item=><div className="followup-row" key={item.id}><span className={`date-tile ${item.display_status==='Overdue'?'hot':''}`}><b>{date(item.scheduled_at||item.next_follow_up_date,{day:'2-digit'})}</b><small>{date(item.scheduled_at||item.next_follow_up_date,{month:'short'}).toUpperCase()}</small></span><div><b>{item.business_name}</b><small>{item.customer_name} · {item.customer_type}</small><p>{item.note}</p><small>{item.created_by_name} · {date(item.scheduled_at,{dateStyle:'medium',timeStyle:'short'})}</small></div><strong className={item.display_status==='Overdue'?'overdue':''}>{item.display_status}</strong>{item.status==='Pending'&&<div className="row-actions"><button disabled={busy} onClick={()=>setCompleting(item)}><Check/>Complete</button><button disabled={busy} onClick={()=>setReschedule({...item,next_at:'',new_note:''})}><Clock3/>Reschedule</button></div>}<button className="icon-button" aria-label={`Open ${item.business_name}`} onClick={()=>navigate(`/customers/${item.customer_id}`)}><ChevronRight/></button></div>)}</div><Pagination meta={data.meta} onPage={page=>setQuery(current=>({...current,page}))}/></>:<EmptyState title="No follow-ups in this view" message="Your schedule is clear. Try another agenda tab or adjust the filters."/>}</section>
 <ConfirmDialog open={Boolean(completing)} onClose={()=>setCompleting(null)} onConfirm={complete} title="Complete this follow-up?" message={completing?`${completing.business_name} will be marked complete.`:''} confirmLabel="Complete follow-up" tone="primary" loading={busy}/>
 <Modal open={Boolean(reschedule)} onClose={()=>setReschedule(null)} title="Reschedule follow-up" subtitle={reschedule?.business_name}>{reschedule&&<form onSubmit={saveReschedule}><Field label="New date and time"><input type="datetime-local" required value={reschedule.next_at} onChange={e=>setReschedule({...reschedule,next_at:e.target.value})}/></Field><Field label="Updated note" hint="Optional"><textarea value={reschedule.new_note} onChange={e=>setReschedule({...reschedule,new_note:e.target.value})}/></Field><div className="form-actions"><button type="button" className="secondary" onClick={()=>setReschedule(null)}>Cancel</button><button className="primary" disabled={busy}>{busy?'Rescheduling…':'Reschedule'}</button></div></form>}</Modal></>;
}
