import {useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {ArrowRight,ChevronDown,Eye,EyeOff,LockKeyhole,ShieldCheck} from 'lucide-react';
import {useAuth} from '../context/AuthContext.jsx';

const accounts=[['Admin','admin@orbit.local','Full workspace'],['Sales','sales@orbit.local','CRM and challans'],['Warehouse','warehouse@orbit.local','Products and stock'],['Accounts','accounts@orbit.local','Sales and analytics']];

export default function Login(){
  const {login}=useAuth();const navigate=useNavigate();
  const [form,setForm]=useState({email:'admin@orbit.local',password:'Orbit@123'});
  const [remember,setRemember]=useState(true),[show,setShow]=useState(false),[demos,setDemos]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const submit=async event=>{event.preventDefault();setBusy(true);setError('');try{await login(form,{remember});navigate('/')}catch(err){setError(err.message)}finally{setBusy(false)}};
  return <div className="login-page">
    <section className="login-visual warehouse" aria-label="Orbit operations workspace"><img src="/assets/orbit-warehouse-login.jpg" alt="Organized wholesale distribution warehouse"/><div className="login-overlay"/><div className="login-brand"><span>O</span>Orbit</div><div className="hero-copy"><p className="eyebrow">OPERATIONS INTELLIGENCE</p><h1>Run your operations<br/>with clarity.</h1><p>CRM, inventory and sales workflows in one intelligent workspace.</p></div><div className="warehouse-proof"><div><span>LIVE INVENTORY</span><b>20 products</b></div><div><span>WORKFLOW CONTROL</span><b>Atomic stock updates</b></div></div><footer>Built for wholesale and distribution teams</footer></section>
    <section className="login-panel"><form onSubmit={submit}><div className="mobile-brand"><span>O</span>Orbit</div><div className="security"><ShieldCheck/>Protected workspace</div><h2>Welcome back</h2><p>Sign in to Orbit ERP.</p>{error&&<div className="form-error" role="alert">{error}</div>}<label className="field"><span>Work email</span><input type="email" autoComplete="email" value={form.email} onChange={event=>setForm({...form,email:event.target.value})} required/></label><label className="field"><span>Password</span><div className="input-icon"><LockKeyhole/><input type={show?'text':'password'} autoComplete="current-password" value={form.password} onChange={event=>setForm({...form,password:event.target.value})} required/><button type="button" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(value=>!value)}>{show?<EyeOff/>:<Eye/>}</button></div></label><label className="remember-session"><input type="checkbox" checked={remember} onChange={event=>setRemember(event.target.checked)}/><span>Remember me on this device</span></label><button className="primary login-button" disabled={busy}>{busy?'Signing in…':<>Sign in <ArrowRight/></>}</button><div className="demo-accounts"><button type="button" aria-expanded={demos} onClick={()=>setDemos(value=>!value)}><div><b>Demo accounts</b><small>All use password Orbit@123</small></div><ChevronDown className={demos?'open':''}/></button>{demos&&<div>{accounts.map(([role,email,scope])=><button type="button" key={role} onClick={()=>setForm({email,password:'Orbit@123'})}><span>{role[0]}</span><div><b>{role}</b><small>{scope}</small></div><ArrowRight/></button>)}</div>}</div><p className="demo-disclaimer">Assignment environment · Never use these credentials in production.</p></form></section>
  </div>;
}
