import{useCallback,useEffect,useState}from'react';
import{useSearchParams}from'react-router-dom';
import{ArrowDownLeft,ArrowUpRight,Boxes,Filter,History,MapPin,MoreHorizontal,Plus,TriangleAlert,Search}from'lucide-react';
import{api,queryString}from'../lib/api.js';
import{currency,date}from'../lib/format.js';
import{Badge,EmptyState,ErrorState,Field,Loading,Modal,Pagination}from'../components/UI.jsx';
import{useAuth}from'../context/AuthContext.jsx';
import{useToast}from'../context/ToastContext.jsx';
const empty={product_name:'',sku:'',category:'',unit_price:'',initial_stock:0,minimum_stock:0,warehouse_location:''};
export default function Products(){
 const[params,setParams]=useSearchParams(),[data,setData]=useState(null),[error,setError]=useState('');
 const[query,setQuery]=useState({search:'',stock:params.get('stock')||'',page:1}),[editing,setEditing]=useState(params.get('create')==='1'?empty:null),[selected,setSelected]=useState(null),[selectedError,setSelectedError]=useState(''),[movement,setMovement]=useState(null);
 const toast=useToast(),{can}=useAuth();
 const load=useCallback(async()=>{setError('');try{setData(await api(`/products${queryString(query)}`))}catch(e){setError(e.message);setData(null)}},[query]);
 const openProduct=async id=>{setSelectedError('');setSelected({id,loading:true});try{setSelected(await api(`/products/${id}`))}catch(e){setSelectedError(e.message);setSelected({id,error:true})}};
 useEffect(()=>{const t=setTimeout(load,200);return()=>clearTimeout(t)},[load]);
 useEffect(()=>{const product=params.get('product');if(product)openProduct(product)},[params]);
 const save=async e=>{e.preventDefault();try{await api(editing.id?`/products/${editing.id}`:'/products',{method:editing.id?'PUT':'POST',body:editing});toast(editing.id?'Product updated.':'Product added to inventory.');setEditing(null);setParams({});await load()}catch(e){toast(e.message,'error')}};
 const adjust=async e=>{e.preventDefault();try{await api(`/products/${movement.product.id}/movements`,{method:'POST',body:movement});toast('Stock balance updated.');setMovement(null);await load()}catch(e){toast(e.message,'error')}};
 return <><div className="page-heading"><div><div className="eyebrow neutral"><Boxes/> INVENTORY CONTROL</div><h1>Products & stock</h1><p>Real-time visibility across every SKU and warehouse.</p></div>{can('Admin','Warehouse')&&<button className="primary" onClick={()=>setEditing(empty)}><Plus/>Add product</button>}</div><div className="inventory-strip"><span><i className="good"/><b>{data?.data.filter(p=>!p.low_stock).length||0}</b> healthy in view</span><span><i className="warning"/><b>{data?.data.filter(p=>p.low_stock).length||0}</b> low stock in view</span><small>Stock status updates automatically after confirmed challans</small></div><div className="panel list-panel"><div className="list-toolbar"><div className="search-input"><Search/><input value={query.search} onChange={e=>setQuery({...query,search:e.target.value,page:1})} placeholder="Search product, SKU, category…"/></div><div className="toolbar-spacer"/><Filter/><select value={query.stock} onChange={e=>setQuery({...query,stock:e.target.value,page:1})}><option value="">All stock</option><option value="healthy">Healthy</option><option value="low">Low stock</option></select></div>{error?<ErrorState title="Unable to load inventory" message={error} retry={load}/>:!data?<Loading/>:data.data.length?<><div className="table-wrap"><table><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Stock level</th><th>Location</th><th/></tr></thead><tbody>{data.data.map(p=><tr key={p.id} onClick={()=>openProduct(p.id)}><td><div className="entity"><span className={`product-icon ${p.low_stock?'low':''}`}><Boxes/></span><div><b>{p.product_name}</b><small>{p.sku}</small></div></div></td><td><span className="soft-tag">{p.category}</span></td><td><b>{currency(p.unit_price)}</b></td><td><div className="stock-cell"><div><b>{p.current_stock}</b><small>/ min {p.minimum_stock}</small></div><div className="stock-bar"><i style={{width:`${Math.min(100,p.current_stock/Math.max(p.minimum_stock,1)*55)}%`}} className={p.low_stock?'low':''}/></div>{p.low_stock&&<span><TriangleAlert/>Low</span>}</div></td><td><span className="location"><MapPin/>{p.warehouse_location}</span></td><td><button aria-label={`Open ${p.product_name}`} className="icon-button"><MoreHorizontal/></button></td></tr>)}</tbody></table></div><Pagination meta={data.meta} onPage={page=>setQuery({...query,page})}/></>:<EmptyState title="No products found"/>}</div><ProductForm value={editing} setValue={setEditing} close={()=>{setEditing(null);setParams({})}} save={save}/><ProductDrawer value={selected} error={selectedError} retry={()=>openProduct(selected.id)} close={()=>{setSelected(null);setParams({})}} canEdit={can('Admin','Warehouse')} edit={()=>{setEditing(selected);setSelected(null)}} move={type=>{setMovement({product:selected,movement_type:type,quantity:1,reason:''});setSelected(null)}}/><MovementModal value={movement} setValue={setMovement} close={()=>setMovement(null)} save={adjust}/></>;
}
function ProductForm({value,setValue,close,save}){if(!value)return null;const set=(k,v)=>setValue({...value,[k]:v});return <Modal open title={value.id?'Edit product':'Add product'} subtitle="Create a trackable SKU with its stock threshold." onClose={close} size="large"><form onSubmit={save} className="form-grid"><Field label="Product name"><input value={value.product_name} onChange={e=>set('product_name',e.target.value)} required/></Field><Field label="SKU / code"><input value={value.sku} onChange={e=>set('sku',e.target.value)} required/></Field><Field label="Category"><input value={value.category} onChange={e=>set('category',e.target.value)} required/></Field><Field label="Unit price"><input type="number" min="0" value={value.unit_price} onChange={e=>set('unit_price',e.target.value)} required/></Field>{!value.id&&<Field label="Opening stock"><input type="number" min="0" value={value.initial_stock} onChange={e=>set('initial_stock',e.target.value)} required/></Field>}<Field label="Minimum alert quantity"><input type="number" min="0" value={value.minimum_stock} onChange={e=>set('minimum_stock',e.target.value)} required/></Field><Field label="Warehouse location"><input value={value.warehouse_location} onChange={e=>set('warehouse_location',e.target.value)} required/></Field><div className="form-actions full"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary">Save product</button></div></form></Modal>}
function ProductDrawer({value,error,retry,close,canEdit,edit,move}){const[movements,setMovements]=useState(null),[movementError,setMovementError]=useState(''),[page,setPage]=useState(1);const load=useCallback(async()=>{if(!value?.id||value.loading||value.error)return;setMovementError('');try{setMovements(await api(`/products/${value.id}/movements?page=${page}&limit=10`))}catch(e){setMovementError(e.message);setMovements(null)}},[value?.id,value?.loading,value?.error,page]);useEffect(()=>{load()},[load]);if(!value)return null;return <div className="drawer-backdrop" onClick={e=>e.target===e.currentTarget&&close()}><aside className="drawer">{value.loading?<Loading/>:value.error?<ErrorState title="Unable to load product" message={error} retry={retry}/>:<><header><div><small>PRODUCT DETAILS</small><h2>{value.product_name}</h2><p>{value.sku}</p></div><button aria-label="Close product" onClick={close}>×</button></header><div className={`stock-spotlight ${value.low_stock?'low':''}`}><span>Available stock</span><strong>{value.current_stock}<small>units</small></strong><Badge>{value.low_stock?'Low stock':'Healthy'}</Badge></div><dl><div><dt>Unit price</dt><dd>{currency(value.unit_price)}</dd></div><div><dt>Category</dt><dd>{value.category}</dd></div><div><dt>Minimum level</dt><dd>{value.minimum_stock} units</dd></div><div><dt>Warehouse</dt><dd>{value.warehouse_location}</dd></div></dl>{canEdit&&<div className="drawer-actions"><button className="stock-in" onClick={()=>move('IN')}><ArrowDownLeft/>Stock in</button><button className="stock-out" onClick={()=>move('OUT')}><ArrowUpRight/>Stock out</button><button className="secondary" onClick={edit}>Edit product</button></div>}<h3><History/>Movement history</h3>{movementError?<ErrorState title="Unable to load movement history" message={movementError} retry={load}/>:!movements?<Loading/>:movements.data.length?<><div className="movement-list">{movements.data.map(m=><div key={m.id}><i className={m.movement_type}/><div><b>{m.challan_number?`${m.reason} ${m.challan_number}`:m.reason}</b><small>{m.created_by_name||'System'} · {date(m.created_at,{dateStyle:'medium',timeStyle:'short'})}</small></div><strong className={m.movement_type}>{m.movement_type==='IN'?'+':'−'}{m.quantity_changed}</strong></div>)}</div><Pagination meta={movements.meta} onPage={setPage}/></>:<EmptyState title="No stock movement yet"/>}</>}</aside></div>}
function MovementModal({value,setValue,close,save}){if(!value)return null;return <Modal open title={`${value.movement_type==='IN'?'Receive':'Issue'} stock`} subtitle={`${value.product.product_name} · ${value.product.current_stock} currently available`} onClose={close}><form onSubmit={save}><Field label="Quantity"><input type="number" min="1" value={value.quantity} onChange={e=>setValue({...value,quantity:e.target.value})} required/></Field><Field label="Reason"><textarea value={value.reason} onChange={e=>setValue({...value,reason:e.target.value})} placeholder="e.g. Supplier delivery, damaged goods…" required/></Field><div className="form-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary">Update stock</button></div></form></Modal>}
