import{useCallback,useEffect,useState}from'react';import{useNavigate,useSearchParams}from'react-router-dom';
import{Boxes,Filter,Image as ImageIcon,MapPin,MoreHorizontal,Plus,Search,X}from'lucide-react';
import{api,queryString}from'../lib/api.js';import{currency}from'../lib/format.js';
import{Badge,EmptyState,ErrorState,Field,Modal,Pagination,TableSkeleton}from'../components/UI.jsx';import{useAuth}from'../context/AuthContext.jsx';import{useToast}from'../context/ToastContext.jsx';
const empty={product_name:'',sku:'',category:'',unit_price:'',initial_stock:0,minimum_stock:0,warehouse_location:'',image_url:''};
export default function Products(){
 const[params,setParams]=useSearchParams(),navigate=useNavigate(),toast=useToast(),{can}=useAuth();
 const[data,setData]=useState(null),[error,setError]=useState(''),[editing,setEditing]=useState(params.get('create')==='1'?empty:null),[busy,setBusy]=useState(false);
 const[query,setQuery]=useState({search:'',stock:params.get('stock')||'',category:'',warehouse:'',sort:'updated',direction:'desc',page:1,limit:10});
 const load=useCallback(async()=>{setError('');try{setData(await api(`/products${queryString(query)}`))}catch(err){setData(null);setError(err.message)}},[query]);useEffect(()=>{const timer=setTimeout(load,220);return()=>clearTimeout(timer)},[load]);useEffect(()=>{if(params.get('create')==='1')setEditing(empty);const product=params.get('product');if(product)navigate(`/products/${product}`,{replace:true})},[params,navigate]);
 const set=(key,value)=>setQuery(current=>({...current,[key]:value,page:1}));const clear=()=>setQuery({search:'',stock:'',category:'',warehouse:'',sort:'updated',direction:'desc',page:1,limit:10});
 const save=async event=>{event.preventDefault();setBusy(true);try{await api(editing.id?`/products/${editing.id}`:'/products',{method:editing.id?'PUT':'POST',body:editing});toast.success(editing.id?'Product updated':'Product created');setEditing(null);setParams({});await load()}catch(err){toast.error(err.message)}finally{setBusy(false)}};
 const summary=data?.summary;
 return <><div className="page-heading"><div><div className="eyebrow neutral"><Boxes/> INVENTORY CONTROL</div><h1>Products & stock</h1><p>Real-time visibility across every SKU and warehouse.</p></div>{can('Admin','Warehouse')&&<button className="primary" onClick={()=>setEditing(empty)}><Plus/>Add product</button>}</div>
 {summary&&<section className="inventory-summary"><div><small>Total products</small><b>{summary.total_products}</b></div><div><small>Inventory value</small><b>{currency(summary.inventory_value)}</b></div><div><small>Healthy</small><b>{summary.healthy_stock}</b></div><div><small>Low stock</small><b>{summary.low_stock}</b></div><div><small>Out of stock</small><b>{summary.out_of_stock}</b></div></section>}
 <section className="panel list-panel"><div className="list-toolbar"><div className="search-input"><Search/><input value={query.search} onChange={e=>set('search',e.target.value)} placeholder="Search product or SKU…"/></div><Filter/><select value={query.category} onChange={e=>set('category',e.target.value)}><option value="">All categories</option>{data?.facets?.categories?.map(value=><option key={value}>{value}</option>)}</select><select value={query.warehouse} onChange={e=>set('warehouse',e.target.value)}><option value="">All warehouses</option>{data?.facets?.warehouses?.map(value=><option key={value}>{value}</option>)}</select><select value={query.stock} onChange={e=>set('stock',e.target.value)}><option value="">All health</option><option value="healthy">Healthy</option><option value="low">Low stock</option><option value="out">Out of stock</option></select><select value={`${query.sort}:${query.direction}`} onChange={e=>{const[sort,direction]=e.target.value.split(':');setQuery({...query,sort,direction,page:1})}}><option value="updated:desc">Recently updated</option><option value="name:asc">Name A–Z</option><option value="stock:asc">Lowest stock</option><option value="price:desc">Highest price</option></select>{Object.entries(query).some(([key,value])=>!['page','limit','sort','direction'].includes(key)&&value)&&<button className="clear-filter" onClick={clear}><X/>Clear</button>}</div>
 {error?<ErrorState title="Unable to load inventory" message={error} retry={load}/>:!data?<TableSkeleton columns={8}/>:data.data.length?<><div className="table-wrap"><table><thead><tr><th>Product</th><th>SKU</th><th>Category</th><th>Price</th><th>Current</th><th>Minimum</th><th>Warehouse</th><th>Health</th><th/></tr></thead><tbody>{data.data.map(product=><tr tabIndex="0" key={product.id} onClick={()=>navigate(`/products/${product.id}`)} onKeyDown={e=>e.key==='Enter'&&navigate(`/products/${product.id}`)}><td><div className="entity"><ProductVisual product={product}/><b>{product.product_name}</b></div></td><td>{product.sku}</td><td><span className="soft-tag">{product.category}</span></td><td><b>{currency(product.unit_price)}</b></td><td><strong>{product.current_stock}</strong></td><td>{product.minimum_stock}</td><td><span className="location"><MapPin/>{product.warehouse_location}</span></td><td><Badge>{product.stock_health}</Badge></td><td><button className="icon-button" aria-label={`Open ${product.product_name}`}><MoreHorizontal/></button></td></tr>)}</tbody></table></div><Pagination meta={data.meta} onPage={page=>setQuery(current=>({...current,page}))}/></>:<EmptyState title="No products match these filters" message="Clear filters or create a new inventory product." action={<button className="secondary" onClick={clear}>Clear filters</button>}/>}</section>
 <ProductForm value={editing} setValue={setEditing} close={()=>{setEditing(null);setParams({})}} save={save} busy={busy}/></>;
}
export function ProductVisual({product,size=''}){return <span className={`product-visual ${size}`}>{product.image_url?<img src={product.image_url} alt=""/>:<ImageIcon/>}</span>}
function ProductForm({value,setValue,close,save,busy}){if(!value)return null;const set=(key,next)=>setValue({...value,[key]:next});return <Modal open title={value.id?'Edit product':'Add product'} subtitle="Create a trackable SKU with its stock threshold." onClose={close} size="large"><form onSubmit={save} className="form-grid"><Field label="Product name" required><input value={value.product_name} onChange={e=>set('product_name',e.target.value)} required/></Field><Field label="SKU / code" required><input value={value.sku} onChange={e=>set('sku',e.target.value)} required/></Field><Field label="Category" required><input value={value.category} onChange={e=>set('category',e.target.value)} required/></Field><Field label="Unit price" required><input type="number" min="0" step="0.01" value={value.unit_price} onChange={e=>set('unit_price',e.target.value)} required/></Field>{!value.id&&<Field label="Opening stock"><input type="number" min="0" value={value.initial_stock} onChange={e=>set('initial_stock',e.target.value)}/></Field>}<Field label="Minimum alert quantity" required><input type="number" min="0" value={value.minimum_stock} onChange={e=>set('minimum_stock',e.target.value)} required/></Field><Field label="Warehouse location" required><input value={value.warehouse_location} onChange={e=>set('warehouse_location',e.target.value)} required/></Field><Field label="Image URL" hint="Optional HTTPS product or category image"><input type="url" value={value.image_url||''} onChange={e=>set('image_url',e.target.value)}/></Field><div className="form-actions full"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':'Save product'}</button></div></form></Modal>}
