import{useCallback,useEffect,useState}from'react';
import{ArrowDownLeft,ArrowUpRight,Filter,History,Search}from'lucide-react';
import{api,queryString}from'../lib/api.js';
import{date}from'../lib/format.js';
import{EmptyState,ErrorState,Loading,Pagination}from'../components/UI.jsx';
export default function StockMovements(){
 const[data,setData]=useState(null),[error,setError]=useState('');
 const[query,setQuery]=useState({search:'',type:'',reason:'',created_by:'',warehouse:'',date_from:'',date_to:'',page:1,limit:15});
 const load=useCallback(async()=>{setError('');try{setData(await api(`/stock-movements${queryString(query)}`))}catch(e){setError(e.message);setData(null)}},[query]);
 useEffect(()=>{const id=setTimeout(load,200);return()=>clearTimeout(id)},[load]);
 const set=(key,value)=>setQuery(v=>({...v,[key]:value,page:1}));
 return <><div className="page-heading"><div><div className="eyebrow neutral"><History/> INVENTORY LEDGER</div><h1>Stock movements</h1><p>Receipts and issues with a complete operator trail.</p></div></div><section className="panel list-panel"><div className="list-toolbar"><div className="search-input"><Search/><input value={query.search} onChange={e=>set('search',e.target.value)} placeholder="Search product or SKU…"/></div><Filter/><select value={query.type} onChange={e=>set('type',e.target.value)}><option value="">IN & OUT</option><option>IN</option><option>OUT</option></select><input value={query.reason} onChange={e=>set('reason',e.target.value)} placeholder="Reason contains…"/><select value={query.created_by} onChange={e=>set('created_by',e.target.value)}><option value="">All operators</option>{data?.facets?.users?.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={query.warehouse} onChange={e=>set('warehouse',e.target.value)}><option value="">All warehouses</option>{data?.facets?.warehouses?.map(x=><option key={x}>{x}</option>)}</select><input aria-label="From date" type="date" value={query.date_from} onChange={e=>set('date_from',e.target.value)}/><input aria-label="To date" type="date" value={query.date_to} onChange={e=>set('date_to',e.target.value)}/></div>{error?<ErrorState title="Unable to load stock movements" message={error} retry={load}/>:!data?<Loading/>:data.data.length?<><div className="table-wrap"><table><thead><tr><th>Product</th><th>SKU</th><th>Type</th><th>Quantity</th><th>Reason</th><th>Created by</th><th>Warehouse</th><th>Timestamp</th></tr></thead><tbody>{data.data.map(m=><tr key={m.id}><td><b>{m.product_name}</b></td><td>{m.sku}</td><td><span className={`movement-symbol ${m.movement_type}`}>{m.movement_type==='IN'?<ArrowDownLeft/>:<ArrowUpRight/>}{m.movement_type}</span></td><td><strong className={m.movement_type}>{m.movement_type==='IN'?'+':'−'}{m.quantity_changed}</strong></td><td>{m.challan_number?`${m.reason} ${m.challan_number}`:m.reason}</td><td>{m.created_by_name||'System'}</td><td>{m.warehouse_location}</td><td>{date(m.created_at,{dateStyle:'medium',timeStyle:'short'})}</td></tr>)}</tbody></table></div><Pagination meta={data.meta} onPage={page=>setQuery(v=>({...v,page}))}/></>:<EmptyState title="No stock movements match these filters" message="Receipts, adjustments, and challan issues will appear here."/>}</section></>;
}
