import {Router} from 'express';
import {getAnalytics,getAuditLogs,getNotifications,globalSearch,markAllNotificationsRead,markNotificationRead} from '../controllers/dashboardController.js';
import {allowRoles} from '../middleware/auth.js';
import {asyncHandler} from '../utils/http.js';
const router=Router();
router.get('/analytics',allowRoles('Admin','Accounts'),asyncHandler(getAnalytics));
router.get('/audit-logs',allowRoles('Admin'),asyncHandler(getAuditLogs));
router.get('/search',asyncHandler(globalSearch));
router.get('/notifications',asyncHandler(getNotifications));
router.patch('/notifications/read-all',asyncHandler(markAllNotificationsRead));
router.patch('/notifications/:id/read',asyncHandler(markNotificationRead));
export default router;
