import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';

const testDatabaseUrl=process.env.TEST_DATABASE_URL;
if(testDatabaseUrl){
 process.env.NODE_ENV='test';
 process.env.DATABASE_URL=testDatabaseUrl;
 process.env.JWT_SECRET='orbit-integration-test-secret';
 process.env.CLIENT_URL='http://localhost:5173';
}

test('PostgreSQL-backed ERP business rules',{skip:!testDatabaseUrl},async t=>{
 const[{default:app},{pool},{config}]=await Promise.all([import('../dist/app.js'),import('../dist/db/pool.js'),import('../dist/config/env.js')]);
 const schema=await fs.readFile(new URL('../src/db/schema.sql',import.meta.url),'utf8');
 await pool.query(schema);
 const server=await new Promise(resolve=>{const instance=app.listen(0,()=>resolve(instance))});
 const base=`http://127.0.0.1:${server.address().port}/api`;
 t.after(async()=>{await new Promise(resolve=>server.close(resolve));await pool.end()});

 const reset=async()=>{
  await pool.query('TRUNCATE audit_logs,stock_movements,challan_items,challans,customer_followups,products,customers,users RESTART IDENTITY CASCADE');
  await pool.query("ALTER SEQUENCE challan_number_seq RESTART WITH 1001");
  const hash=await bcrypt.hash('Orbit@123',4),users={};
  for(const role of ['Admin','Sales','Warehouse','Accounts']){const row=(await pool.query('INSERT INTO users(name,email,password_hash,role) VALUES($1,$2,$3,$4) RETURNING id,name,email,role',[`${role} User`,`${role.toLowerCase()}@test.local`,hash,role])).rows[0];users[role]={...row,token:jwt.sign(row,config.jwtSecret,{expiresIn:'10m',issuer:config.jwtIssuer,audience:config.jwtAudience})}}
  const customer=(await pool.query(`INSERT INTO customers(customer_name,mobile,email,business_name,customer_type,address,status,created_by) VALUES('Buyer','9876543210','buyer@test.local','Buyer Business','Wholesale','Test address','Active',$1) RETURNING *`,[users.Sales.id])).rows[0];
  return{users,customer};
 };
 const product=async(userId,{name='Widget',sku='WIDGET-1',stock=10,price=25}={})=>(await pool.query(`INSERT INTO products(product_name,sku,category,unit_price,current_stock,minimum_stock,warehouse_location,created_by) VALUES($1,$2,'Test',$3,$4,2,'Test Warehouse',$5) RETURNING *`,[name,sku,price,stock,userId])).rows[0];
 const request=async(path,token,{method='GET',body}={})=>{const response=await fetch(`${base}${path}`,{method,headers:{Authorization:`Bearer ${token}`,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const json=await response.json();return{status:response.status,body:json}};
 const createChallan=(token,customerId,items,status='Draft')=>request('/challans',token,{method:'POST',body:{customer_id:customerId,items,status,notes:'Integration test'}});
 const stock=async id=>(await pool.query('SELECT current_stock FROM products WHERE id=$1',[id])).rows[0].current_stock;

 await t.test('Draft challan does not alter stock',async()=>{const{users,customer}=await reset(),p=await product(users.Admin.id);const result=await createChallan(users.Sales.token,customer.id,[{product_id:p.id,quantity:4}]);assert.equal(result.status,201);assert.equal(await stock(p.id),10);assert.equal((await pool.query('SELECT COUNT(*)::int count FROM stock_movements')).rows[0].count,0)});
 await t.test('Confirmed challan reduces stock and records a movement',async()=>{const{users,customer}=await reset(),p=await product(users.Admin.id);const result=await createChallan(users.Sales.token,customer.id,[{product_id:p.id,quantity:4}],'Confirmed');assert.equal(result.status,201);assert.equal(await stock(p.id),6);assert.equal((await pool.query("SELECT COUNT(*)::int count FROM stock_movements WHERE movement_type='OUT'")).rows[0].count,1)});
 await t.test('Insufficient stock returns 409 without changing stock',async()=>{const{users,customer}=await reset(),p=await product(users.Admin.id,{stock:3});const result=await createChallan(users.Sales.token,customer.id,[{product_id:p.id,quantity:4}],'Confirmed');assert.equal(result.status,409);assert.equal(result.body.error.code,'INSUFFICIENT_STOCK');assert.equal(await stock(p.id),3)});
 await t.test('Failed multi-item confirmation rolls back every stock change',async()=>{const{users,customer}=await reset(),first=await product(users.Admin.id,{sku:'FIRST',stock:10}),second=await product(users.Admin.id,{name:'Second',sku:'SECOND',stock:1});const result=await createChallan(users.Sales.token,customer.id,[{product_id:first.id,quantity:3},{product_id:second.id,quantity:2}],'Confirmed');assert.equal(result.status,409);assert.equal(await stock(first.id),10);assert.equal(await stock(second.id),1);assert.equal((await pool.query('SELECT COUNT(*)::int count FROM challans')).rows[0].count,0)});
 await t.test('Re-confirming a confirmed challan is rejected',async()=>{const{users,customer}=await reset(),p=await product(users.Admin.id);const created=await createChallan(users.Sales.token,customer.id,[{product_id:p.id,quantity:2}],'Confirmed');const result=await request(`/challans/${created.body.data.id}/status`,users.Sales.token,{method:'PATCH',body:{status:'Confirmed'}});assert.equal(result.status,409);assert.equal(await stock(p.id),8)});
 await t.test('Cancelling a confirmed challan restores stock',async()=>{const{users,customer}=await reset(),p=await product(users.Admin.id);const created=await createChallan(users.Sales.token,customer.id,[{product_id:p.id,quantity:3}],'Confirmed');const result=await request(`/challans/${created.body.data.id}/status`,users.Sales.token,{method:'PATCH',body:{status:'Cancelled'}});assert.equal(result.status,200);assert.equal(await stock(p.id),10);assert.equal((await pool.query("SELECT COUNT(*)::int count FROM stock_movements WHERE movement_type='IN'")).rows[0].count,1)});
 await t.test('Manual IN updates stock',async()=>{const{users}=await reset(),p=await product(users.Admin.id);const result=await request(`/products/${p.id}/movements`,users.Warehouse.token,{method:'POST',body:{movement_type:'IN',quantity:5,reason:'Supplier delivery'}});assert.equal(result.status,201);assert.equal(await stock(p.id),15)});
 await t.test('Manual OUT updates stock',async()=>{const{users}=await reset(),p=await product(users.Admin.id);const result=await request(`/products/${p.id}/movements`,users.Warehouse.token,{method:'POST',body:{movement_type:'OUT',quantity:4,reason:'Damaged units'}});assert.equal(result.status,201);assert.equal(await stock(p.id),6)});
 await t.test('Manual OUT cannot make stock negative',async()=>{const{users}=await reset(),p=await product(users.Admin.id,{stock:2});const result=await request(`/products/${p.id}/movements`,users.Warehouse.token,{method:'POST',body:{movement_type:'OUT',quantity:3,reason:'Invalid issue'}});assert.equal(result.status,409);assert.equal(await stock(p.id),2)});
 await t.test('Challan product snapshot survives catalogue edits',async()=>{const{users,customer}=await reset(),p=await product(users.Admin.id,{name:'Original',price:25});const created=await createChallan(users.Sales.token,customer.id,[{product_id:p.id,quantity:1}]);const updated=await request(`/products/${p.id}`,users.Admin.token,{method:'PUT',body:{product_name:'Renamed',sku:p.sku,category:p.category,unit_price:99,minimum_stock:p.minimum_stock,warehouse_location:p.warehouse_location}});assert.equal(updated.status,200);const detail=await request(`/challans/${created.body.data.id}`,users.Sales.token);assert.equal(detail.body.data.items[0].product_name,'Original');assert.equal(Number(detail.body.data.items[0].unit_price),25)});
 await t.test('Concurrent confirmations cannot produce negative stock',async()=>{const{users,customer}=await reset(),p=await product(users.Admin.id,{stock:5});const[first,second]=await Promise.all([createChallan(users.Sales.token,customer.id,[{product_id:p.id,quantity:4}]),createChallan(users.Sales.token,customer.id,[{product_id:p.id,quantity:4}])]);const results=await Promise.all([request(`/challans/${first.body.data.id}/status`,users.Sales.token,{method:'PATCH',body:{status:'Confirmed'}}),request(`/challans/${second.body.data.id}/status`,users.Sales.token,{method:'PATCH',body:{status:'Confirmed'}})]);assert.deepEqual(results.map(x=>x.status).sort(),[200,409]);assert.equal(await stock(p.id),1)});
 await t.test('Multi-product confirmations lock rows deterministically',async()=>{const{users,customer}=await reset(),first=await product(users.Admin.id,{sku:'LOCK-A',stock:10}),second=await product(users.Admin.id,{name:'Lock B',sku:'LOCK-B',stock:10});const results=await Promise.all([createChallan(users.Sales.token,customer.id,[{product_id:first.id,quantity:2},{product_id:second.id,quantity:3}],'Confirmed'),createChallan(users.Sales.token,customer.id,[{product_id:second.id,quantity:2},{product_id:first.id,quantity:3}],'Confirmed')]);assert.deepEqual(results.map(result=>result.status),[201,201]);assert.equal(await stock(first.id),5);assert.equal(await stock(second.id),5)});
 await t.test('Role-restricted read APIs return 403 and scoped lists hide drafts',async()=>{const{users,customer}=await reset(),p=await product(users.Admin.id);const draft=await createChallan(users.Sales.token,customer.id,[{product_id:p.id,quantity:1}]),confirmed=await createChallan(users.Sales.token,customer.id,[{product_id:p.id,quantity:1}],'Confirmed');assert.equal((await request('/customers',users.Warehouse.token)).status,403);assert.equal((await request('/customers',users.Accounts.token)).status,403);assert.equal((await request('/products',users.Accounts.token)).status,403);assert.equal((await request('/stock-movements',users.Sales.token)).status,403);assert.equal((await request('/products',users.Sales.token)).status,200);assert.equal((await request(`/challans/${draft.body.data.id}`,users.Accounts.token)).status,403);const list=await request('/challans',users.Accounts.token);assert.equal(list.status,200);assert.deepEqual(list.body.data.data.map(x=>x.id),[confirmed.body.data.id])});
 await t.test('All four dashboards and global searches are role scoped',async()=>{const{users,customer}=await reset(),p=await product(users.Admin.id,{name:'Buyer Widget'});await createChallan(users.Sales.token,customer.id,[{product_id:p.id,quantity:1}]);await createChallan(users.Sales.token,customer.id,[{product_id:p.id,quantity:1}],'Confirmed');for(const role of ['Admin','Sales','Warehouse','Accounts'])assert.equal((await request('/dashboard',users[role].token)).status,200);const admin=(await request('/search?q=Buyer',users.Admin.token)).body.data,sales=(await request('/search?q=Buyer',users.Sales.token)).body.data,warehouse=(await request('/search?q=Buyer',users.Warehouse.token)).body.data,accounts=(await request('/search?q=Buyer',users.Accounts.token)).body.data;assert.equal(admin.customers.length,1);assert.equal(admin.products.length,1);assert.equal(admin.challans.length,2);assert.equal(sales.customers.length,1);assert.equal(sales.products.length,1);assert.equal(sales.challans.length,2);assert.equal(warehouse.customers.length,0);assert.equal(warehouse.products.length,1);assert.equal(warehouse.challans.length,1);assert.equal(accounts.customers.length,0);assert.equal(accounts.products.length,0);assert.equal(accounts.challans.length,1);const accountDashboard=(await request('/dashboard',users.Accounts.token)).body.data,warehouseDashboard=(await request('/dashboard',users.Warehouse.token)).body.data;assert.deepEqual(accountDashboard.customerStatus,[]);assert.deepEqual(accountDashboard.inventoryHealth,[]);assert.deepEqual(warehouseDashboard.followups,[]);assert.deepEqual(warehouseDashboard.revenueTrend,[])});
 await t.test('Follow-ups can be completed and rescheduled with history',async()=>{const{users,customer}=await reset();const first=(await pool.query(`INSERT INTO customer_followups(customer_id,note,next_follow_up_date,scheduled_at,created_by) VALUES($1,'Call buyer',CURRENT_DATE,NOW()-INTERVAL '1 hour',$2) RETURNING id`,[customer.id,users.Sales.id])).rows[0];let list=await request('/followups?status=Overdue',users.Sales.token);assert.equal(list.status,200);assert.equal(list.body.data.data[0].display_status,'Overdue');const completed=await request(`/followups/${first.id}/complete`,users.Sales.token,{method:'PATCH',body:{}});assert.equal(completed.status,200);assert.ok(completed.body.data.completed_at);const second=(await pool.query(`INSERT INTO customer_followups(customer_id,note,next_follow_up_date,scheduled_at,created_by) VALUES($1,'Pricing review',CURRENT_DATE,NOW()+INTERVAL '1 hour',$2) RETURNING id`,[customer.id,users.Sales.id])).rows[0];const next=new Date(Date.now()+86400000).toISOString();const rescheduled=await request(`/followups/${second.id}/reschedule`,users.Sales.token,{method:'POST',body:{scheduled_at:next,note:'Pricing review tomorrow'}});assert.equal(rescheduled.status,201);const history=await request(`/customers/${customer.id}`,users.Sales.token);assert.equal(history.body.data.followups.filter(x=>x.status==='Completed').length,1);assert.equal(history.body.data.followups.filter(x=>x.status==='Rescheduled').length,1);assert.equal(history.body.data.followups.filter(x=>x.status==='Pending').length,1)});
 await t.test('Notifications persist per-user read state',async()=>{const{users}=await reset();await product(users.Admin.id,{stock:1});const first=await request('/notifications',users.Admin.token);assert.equal(first.status,200);assert.ok(first.body.data.unread>0);const id=first.body.data.items[0].id;const read=await request(`/notifications/${id}/read`,users.Admin.token,{method:'PATCH'});assert.equal(read.status,200);const second=await request('/notifications',users.Admin.token);assert.equal(second.body.data.items.find(item=>item.id===id).read_at!==null,true);const all=await request('/notifications/read-all',users.Admin.token,{method:'PATCH'});assert.equal(all.status,200);assert.equal((await request('/notifications',users.Admin.token)).body.data.unread,0)});
});
