import{useEffect,useMemo,useRef,useState}from'react';import{NavLink,useLocation,useNavigate}from'react-router-dom';import{BarChart3,Bell,Boxes,CalendarClock,ChevronRight,ClipboardList,Command,History,LayoutDashboard,LogOut,Menu,Moon,Plus,ReceiptText,Search,Sun,UsersRound,X}from'lucide-react';import{useAuth}from'../context/AuthContext.jsx';import{initials}from'../lib/format.js';import{api}from'../lib/api.js';
const sections=[
 ['Overview',[['/','Dashboard',LayoutDashboard]]],
 ['CRM',[['/customers','Customers',UsersRound,['Admin','Sales']],['/follow-ups','Follow-ups',CalendarClock,['Admin','Sales']]]],
 ['Sales',[['/challans','Challans',ReceiptText]]],
 ['Inventory',[['/products','Products',Boxes,['Admin','Sales','Warehouse']],['/stock-movements','Stock movements',History,['Admin','Warehouse']]]],
 ['Intelligence',[['/analytics','Analytics',BarChart3,['Admin','Accounts']]]],
 ['System',[['/audit-logs','Audit logs',ClipboardList,['Admin']]]],
];
export default function Layout({children}){const{user,logout}=useAuth(),navigate=useNavigate(),location=useLocation();const[mobile,setMobile]=useState(false),[command,setCommand]=useState(false),[notifications,setNotifications]=useState(null);const[theme,setTheme]=useState(()=>localStorage.getItem('orbit_theme')||'system');
 useEffect(()=>{const dark=theme==='dark'||(theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('orbit_theme',theme)},[theme]);useEffect(()=>setMobile(false),[location]);useEffect(()=>{const onKey=e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setCommand(true)}if(e.key==='Escape')setCommand(false)};addEventListener('keydown',onKey);return()=>removeEventListener('keydown',onKey)},[]);
 const visible=sections.map(([label,links])=>[label,links.filter(([, , ,roles])=>!roles||roles.includes(user.role))]).filter(([,links])=>links.length);const create=()=>navigate(user.role==='Warehouse'?'/products?create=1':'/challans/new');const toggleNotifications=async()=>{if(notifications){setNotifications(null);return}setNotifications({loading:true,items:[],unread:0});try{setNotifications(await api('/notifications'))}catch(error){setNotifications({error:error.message,items:[],unread:0})}};
 return <div className="app-shell"><aside className={mobile?'open':''}><div className="brand"><span>O</span><div>Orbit<small>OPERATIONS INTELLIGENCE</small></div><button aria-label="Close navigation" onClick={()=>setMobile(false)}><X/></button></div><nav>{visible.map(([label,links])=><div className="nav-section" key={label}><small>{label}</small>{links.map(([to,text,Icon])=><NavLink to={to} key={to} end={to==='/'}><Icon/><span>{text}</span></NavLink>)}</div>)}</nav><div className="profile"><span className="avatar">{initials(user.name)}</span><div><b>{user.name}</b><small>{user.role}</small></div><button title="Sign out" onClick={()=>{logout();navigate('/login')}}><LogOut/></button></div></aside>{mobile&&<div className="mobile-scrim" onClick={()=>setMobile(false)}/>}<main><header className="topbar"><button className="mobile-menu" aria-label="Open navigation" onClick={()=>setMobile(true)}><Menu/></button><div className="breadcrumb"><small>ORBIT ERP</small><b>{document.title||'Operations workspace'}</b></div><button className="command-trigger" onClick={()=>setCommand(true)}><Search/><span>Search customers, products, challans…</span><kbd>⌘ K</kbd></button><div className="top-actions"><button aria-label={`Theme: ${theme}`} title={`Theme: ${theme}`} onClick={()=>setTheme(theme==='system'?'light':theme==='light'?'dark':'system')}>{theme==='light'?<Sun/>:<Moon/>}</button><button className="notification" aria-label="Notifications" onClick={toggleNotifications}><Bell/>{notifications?.unread>0&&<i/>}</button>{['Admin','Sales','Warehouse'].includes(user.role)&&<button className="primary compact" onClick={create}><Plus/>{user.role==='Warehouse'?'Product':'New'}</button>}</div>{notifications&&<NotificationPanel data={notifications} close={()=>setNotifications(null)} navigate={navigate}/>}</header><div className="page-container">{children}</div></main>{command&&<CommandPalette close={()=>setCommand(false)} navigate={navigate} user={user}/>}</div>}
function NotificationPanel({data,close,navigate}){return <div className="notification-panel"><header><div><b>Notifications</b><small>{data.loading?'Loading…':data.error?'Unable to load':`${data.unread} items need attention`}</small></div><button onClick={close}><X/></button></header>{data.error?<p>{data.error}. Close and retry.</p>:data.loading?<p>Loading notifications…</p>:data.items.length?data.items.map(item=><button key={item.id} onClick={()=>{navigate(item.to);close()}}><i className={item.type}/><div><b>{item.title}</b><small>{item.message}</small></div><ChevronRight/></button>):<p>Your operation is all clear.</p>}</div>}
function CommandPalette({close,navigate,user}){const[q,setQ]=useState(''),[results,setResults]=useState({customers:[],products:[],challans:[]}),[searchError,setSearchError]=useState(''),[active,setActive]=useState(0),timer=useRef();const commands=useMemo(()=>[
 ['Dashboard','/'],...( ['Admin','Sales'].includes(user.role)?[['Customers','/customers'],['New customer','/customers?create=1'],['Follow-ups','/follow-ups'],['New challan','/challans/new']]:[]),['Challans','/challans'],...(['Admin','Warehouse'].includes(user.role)?[['Products','/products'],['Stock movements','/stock-movements'],['Stock adjustment','/products']]:[]),...(['Admin','Accounts'].includes(user.role)?[['Analytics','/analytics']]:[]),...(user.role==='Admin'?[['Audit logs','/audit-logs']]:[]),
 ].filter(([label])=>label.toLowerCase().includes(q.toLowerCase())),[q,user.role]);useEffect(()=>{clearTimeout(timer.current);setSearchError('');if(q.length<2){setResults({customers:[],products:[],challans:[]});return}timer.current=setTimeout(async()=>{try{setResults(await api(`/search?q=${encodeURIComponent(q)}`))}catch(error){setResults({customers:[],products:[],challans:[]});setSearchError(error.message)}},180);return()=>clearTimeout(timer.current)},[q]);const entities=[...results.customers.map(x=>[`${x.business_name} · ${x.customer_name}`,`/customers/${x.id}`]),...results.products.map(x=>[`${x.product_name} · ${x.sku}`,`/products?product=${x.id}`]),...results.challans.map(x=>[`${x.challan_number} · ${x.business_name}`,`/challans/${x.id}`])];const all=[...commands,...entities];useEffect(()=>setActive(0),[q,all.length]);const go=to=>{navigate(to);close()};return <div className="command-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="command-box" onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();setActive(v=>Math.min(all.length-1,v+1))}if(e.key==='ArrowUp'){e.preventDefault();setActive(v=>Math.max(0,v-1))}if(e.key==='Enter'&&all[active])go(all[active][1])}}><div><Search/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Search Orbit or run a command…"/><kbd>ESC</kbd></div><p>{q.length>=2?'SEARCH RESULTS':'QUICK ACTIONS'}</p>{searchError?<div className="command-empty">Unable to search: {searchError}</div>:all.slice(0,10).map(([label,to],index)=><button className={index===active?'active':''} key={`${to}-${label}`} onMouseEnter={()=>setActive(index)} onClick={()=>go(to)}><Command/><span>{label}</span><small>Open</small></button>)}{!searchError&&!all.length&&<div className="command-empty">No matching customers, products, challans, or commands.</div>}</div></div>}
