import{Children,cloneElement,useEffect,useId,useRef,useState}from'react';
import{AlertTriangle,ChevronDown,ChevronLeft,ChevronRight,Inbox,Info,LoaderCircle,X}from'lucide-react';

export function Button({variant='secondary',size='',loading=false,children,className='',...props}){return <button className={`ui-button ${variant} ${size} ${className}`} disabled={loading||props.disabled} {...props}>{loading&&<LoaderCircle className="spin"/>}{children}</button>}
export function IconButton({label,children,className='',...props}){return <button className={`icon-button ${className}`} aria-label={label} title={props.title||label} {...props}>{children}</button>}
export function Input(props){return <input className="ui-control" {...props}/>}
export function Select({children,...props}){return <select className="ui-control" {...props}>{children}</select>}
export function Textarea(props){return <textarea className="ui-control" {...props}/>}
export function Badge({children,tone}){return <span className={`badge ${tone||String(children).toLowerCase().replaceAll(' ','-')}`}><i/>{children}</span>}
export function Avatar({name='',src,size='md',className=''}){const initials=name.split(' ').filter(Boolean).map(x=>x[0]).join('').slice(0,2).toUpperCase();return <span className={`ui-avatar ${size} ${className}`}>{src?<img src={src} alt="" onError={e=>{e.currentTarget.hidden=true;e.currentTarget.nextElementSibling.hidden=false}}/>:null}<span hidden={Boolean(src)}>{initials||'O'}</span></span>}
export function Card({as:Tag='section',className='',children,...props}){return <Tag className={`panel ui-card ${className}`} {...props}>{children}</Tag>}
export function MetricCard({label,value,detail,icon:Icon,tone='brand'}){return <article className={`metric-card tone-${tone}`}><div><span>{label}</span><strong>{value}</strong>{detail&&<small>{detail}</small>}</div>{Icon&&<i><Icon/></i>}</article>}
export function DataTable({columns,rows,rowKey='id',onRowClick,empty}){if(!rows?.length)return empty||<EmptyState/>;return <div className="table-wrap"><table><thead><tr>{columns.map(column=><th key={column.key} className={column.numeric?'numeric':''}>{column.label}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row[rowKey]} tabIndex={onRowClick?0:undefined} onClick={()=>onRowClick?.(row)} onKeyDown={e=>{if(onRowClick&&(e.key==='Enter'||e.key===' ')){e.preventDefault();onRowClick(row)}}}>{columns.map(column=><td key={column.key} className={column.numeric?'numeric':''}>{column.render?column.render(row):row[column.key]}</td>)}</tr>)}</tbody></table></div>}
export function DropdownMenu({trigger,label='Menu',children,align='right'}){const[open,setOpen]=useState(false),ref=useRef(),triggerRef=useRef();useEffect(()=>{const close=e=>{if(!ref.current?.contains(e.target))setOpen(false)};const key=e=>{if(e.key==='Escape'&&open){setOpen(false);triggerRef.current?.focus()}};document.addEventListener('pointerdown',close);document.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',close);document.removeEventListener('keydown',key)}},[open]);useEffect(()=>{if(open)requestAnimationFrame(()=>ref.current?.querySelector('[role="menuitem"]')?.focus())},[open]);const menuKey=e=>{const items=[...e.currentTarget.querySelectorAll('[role="menuitem"]')],index=items.indexOf(document.activeElement);if(e.key==='ArrowDown'){e.preventDefault();items[(index+1)%items.length]?.focus()}if(e.key==='ArrowUp'){e.preventDefault();items[(index-1+items.length)%items.length]?.focus()}if(e.key==='Home'){e.preventDefault();items[0]?.focus()}if(e.key==='End'){e.preventDefault();items.at(-1)?.focus()}};return <div className="dropdown" ref={ref}><button ref={triggerRef} className="dropdown-trigger" aria-label={label} aria-haspopup="menu" aria-expanded={open} onClick={()=>setOpen(v=>!v)}>{trigger}<ChevronDown/></button>{open&&<div className={`dropdown-menu ${align}`} role="menu" onKeyDown={menuKey} onClick={()=>setOpen(false)}>{children}</div>}</div>}
export function MenuItem({icon:Icon,children,danger=false,...props}){return <button role="menuitem" className={danger?'danger':''} {...props}>{Icon&&<Icon/>}<span>{children}</span></button>}
export function Tooltip({label,children}){return <span className="tooltip" data-tooltip={label}>{children}</span>}
export function Tabs({items,value,onChange,label='Sections'}){return <div className="ui-tabs" role="tablist" aria-label={label}>{items.map(item=><button role="tab" aria-selected={value===item.value} className={value===item.value?'active':''} key={item.value} onClick={()=>onChange(item.value)}>{item.label}</button>)}</div>}

export function Modal({open,onClose,title,subtitle,children,size=''}){const titleId=useId(),dialog=useRef(),restore=useRef();useEffect(()=>{if(!open)return;restore.current=document.activeElement;const node=dialog.current;const focusables=()=>[...node.querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])')];const key=e=>{if(e.key==='Escape'){e.preventDefault();onClose()}if(e.key==='Tab'){const items=focusables(),first=items[0],last=items.at(-1);if(!items.length)return;if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',key);requestAnimationFrame(()=>focusables()[0]?.focus());return()=>{document.removeEventListener('keydown',key);restore.current?.focus?.()}},[open,onClose]);if(!open)return null;return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section ref={dialog} className={`modal ${size}`} role="dialog" aria-modal="true" aria-labelledby={titleId}><header><div><h2 id={titleId}>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><IconButton label="Close dialog" onClick={onClose}><X/></IconButton></header><div className="modal-body">{children}</div></section></div>}
export function Drawer({open=true,onClose,title,subtitle,children,size=''}){const titleId=useId(),drawer=useRef(),restore=useRef();useEffect(()=>{if(!open)return;restore.current=document.activeElement;const node=drawer.current,focusables=()=>[...node.querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),a[href],[tabindex]:not([tabindex="-1"])')];const key=e=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const items=focusables(),first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',key);requestAnimationFrame(()=>focusables()[0]?.focus());return()=>{document.removeEventListener('keydown',key);restore.current?.focus?.()}},[open,onClose]);if(!open)return null;return <div className="drawer-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><aside ref={drawer} className={`drawer ${size}`} role="dialog" aria-modal="true" aria-labelledby={titleId}><header><div><small>{subtitle}</small><h2 id={titleId}>{title}</h2></div><IconButton label="Close drawer" onClick={onClose}><X/></IconButton></header>{children}</aside></div>}
export function ConfirmDialog({open,onClose,onConfirm,title='Confirm action',message,confirmLabel='Confirm',tone='danger',loading=false}){return <Modal open={open} onClose={onClose} title={title} subtitle={message}><div className="confirm-callout"><AlertTriangle/><p>This action may update operational records immediately.</p></div><div className="form-actions"><Button onClick={onClose}>Go back</Button><Button variant={tone} loading={loading} onClick={onConfirm}>{confirmLabel}</Button></div></Modal>}
export function EmptyState({title='Nothing here yet',message='New records will appear here.',action,icon:Icon=Inbox}){return <div className="empty-state"><span><Icon/></span><h3>{title}</h3><p>{message}</p>{action}</div>}
export function ErrorState({title='Unable to load this page',message="We couldn't reach the server. Your data has not been changed.",retry}){return <div className="error-state"><span><AlertTriangle/></span><b>{title}</b><p>{message}</p>{retry&&<Button onClick={retry}>Retry</Button>}</div>}
export function Loading({label='Loading your workspace…'}){return <div className="loading"><LoaderCircle/> {label}</div>}
export function Skeleton({className=''}){return <span className={`skeleton ${className}`} aria-hidden="true"/>}
export function TableSkeleton({rows=6,columns=6}){return <div className="skeleton-table" aria-label="Loading table">{Array.from({length:rows}).map((_,r)=><div key={r}>{Array.from({length:columns}).map((__,c)=><Skeleton key={c}/>)}</div>)}</div>}
export function DashboardSkeleton(){return <div className="dashboard-skeleton"><div className="skeleton-heading"><Skeleton/><Skeleton/></div><div className="skeleton-metrics">{Array.from({length:4}).map((_,i)=><Skeleton key={i}/>)}</div><div className="skeleton-panels"><Skeleton/><Skeleton/><Skeleton/></div></div>}
export function DetailSkeleton(){return <div className="detail-skeleton"><Skeleton className="hero"/><div><Skeleton/><Skeleton/></div></div>}
export function ChartSkeleton(){return <div className="chart-skeleton"><Skeleton/><Skeleton/><Skeleton/><Skeleton/><Skeleton/></div>}
export function Pagination({meta,onPage}){if(!meta||meta.pages<=1)return null;return <div className="pagination"><span>Page <b>{meta.page}</b> of {meta.pages} · {meta.total} results</span><div><IconButton label="Previous page" disabled={meta.page<=1} onClick={()=>onPage(meta.page-1)}><ChevronLeft/></IconButton><IconButton label="Next page" disabled={meta.page>=meta.pages} onClick={()=>onPage(meta.page+1)}><ChevronRight/></IconButton></div></div>}
export function Field({label,error,children,hint,required}){const id=useId(),child=Children.only(children);return <label className={`field ${error?'has-error':''}`} htmlFor={id}><span>{label}{required&&<em> *</em>}</span>{cloneElement(child,{id,'aria-invalid':Boolean(error),'aria-describedby':error?`${id}-error`:undefined})}{hint&&!error&&<small>{hint}</small>}{error&&<small id={`${id}-error`} role="alert">{error}</small>}</label>}
